<?php

namespace App\Http\Controller;
class AliasContainer extends ParametersContainer
{
    //服务别名
    protected $aliases = [];

    //给服务绑定一个别名
    public function alias($alias, $name)
    {
        $this->aliases[$alias] = $name;
    }

    //获取服务
    public function make($name, array $parameters = [])
    {
        //先查找真正的名称
        $name = isset($this->aliases[$name]) ? $this->aliases[$name] : $name;
        return parent::make($name, $parameters); // TODO: Change the autogenerated stub
    }


}